# homelab/gateway/docker-compose.yml
services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - homelab_network # Connect to our new shared network
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    networks:
      - homelab_network

# This block creates the network that palproj will also use.
networks:
  homelab_network:
    driver: bridge
    name: homelab_network # Explicitly naming it is a good practice